// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKIuairsthkPapZAzOeAQp1QYrEI6vxa8',
    appId: '1:93791409800:web:3e46d001112e89f1dc313d',
    messagingSenderId: '93791409800',
    projectId: 'smart-city-zains',
    authDomain: 'smart-city-zains.firebaseapp.com',
    storageBucket: 'smart-city-zains.firebasestorage.app',
    measurementId: 'G-R54SPR8FM2',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoP4GZnhUXnHeoEfKw5MSs8Zs91vcO_sU',
    appId: '1:93791409800:android:0791da08e7793e7fdc313d',
    messagingSenderId: '93791409800',
    projectId: 'smart-city-zains',
    storageBucket: 'smart-city-zains.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG9wh4PnR7z3PYZ0fanxkN5hszizEDvLw',
    appId: '1:93791409800:ios:378467d807a741c1dc313d',
    messagingSenderId: '93791409800',
    projectId: 'smart-city-zains',
    storageBucket: 'smart-city-zains.firebasestorage.app',
    iosBundleId: 'com.example.classiconVsCode',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG9wh4PnR7z3PYZ0fanxkN5hszizEDvLw',
    appId: '1:93791409800:ios:378467d807a741c1dc313d',
    messagingSenderId: '93791409800',
    projectId: 'smart-city-zains',
    storageBucket: 'smart-city-zains.firebasestorage.app',
    iosBundleId: 'com.example.classiconVsCode',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKIuairsthkPapZAzOeAQp1QYrEI6vxa8',
    appId: '1:93791409800:web:102ac20834b9eb2bdc313d',
    messagingSenderId: '93791409800',
    projectId: 'smart-city-zains',
    authDomain: 'smart-city-zains.firebaseapp.com',
    storageBucket: 'smart-city-zains.firebasestorage.app',
    measurementId: 'G-CNV8SMYRQZ',
  );
}
